
// Generated by xt-genmpu.

#include <stdint.h>
#include <xtensa/hal.h>

#if defined (__cplusplus)
extern "C"
#endif
const struct xthal_MPU_entry
__xt_mpu_init_table[] __attribute__((section(".ResetHandler.text"))) = {
  XTHAL_MPU_ENTRY(0x00000000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_WRITEBACK), // flash
  XTHAL_MPU_ENTRY(0x1ffc0000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_NON_CACHEABLE), // dram0
  XTHAL_MPU_ENTRY(0x1ffe0000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_NON_CACHEABLE), // dram1
  XTHAL_MPU_ENTRY(0x20000000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_WRITEBACK), // sram
  XTHAL_MPU_ENTRY(0x20080000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_DEVICE), // entry_table and peripheral
  XTHAL_MPU_ENTRY(0x60301000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_WRITEBACK), // extra_reset_mem
  XTHAL_MPU_ENTRY(0x61000000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
};

#if defined (__cplusplus)
extern "C"
#endif
const uint32_t __xt_mpu_init_table_size __attribute__((section(".ResetHandler.text"))) = 7;

#if defined (__cplusplus)
extern "C"
#endif
const uint8_t __xt_mpu_init_cacheadrdis __attribute__((section(".ResetHandler.text"))) = 0xf4;

#if defined (__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
#include <assert.h>
static_assert(sizeof(__xt_mpu_init_table)/sizeof(__xt_mpu_init_table[0]) == 7, "Incorrect MPU table size");
#endif
